### ISSUE TITLE
Project description

### ISSUE THREAD

**Issue by firminochangani** [doriel/JLO#1]
Hi @doriel, it seems you have done a wonderful work here. 

Just one thing quickly:

It would be nice if you describe what you have done on this repository, technique you used, the data source, everything that you may think is relevant.

Cheers.

**Comment by doriel** [comment]
@flowck Done....

**Comment by pisgo** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
pugong, @cnneter, @leovanzella, @vonwey, @nikilster, @Siunami, @kiyodori, @praguebob, @jbpringuey, @jaromaz, @phpnosql, @lizebang, @sathish76, @peterherrmann, @btyouth, @azizur, @TheMalloum, @JosephCoppola, @davidcorbin, @chujohiroto, @michaelryancaputo, @derouck, @hulvyou, @xiaolongbao, @yupoxiong, @lopezjurip, @Shrikantpaliwal, @andrewdalpino, @FlipFloop, @jinxiaoxi1020, @achillesss, @thaReal, @vexy, @tim5go, @jaxiinofea, @lijinke666, @yhyangjiabin, @rsaha77, @MESS8, @bridgethu, @zhenghenghuo, @vniu, @Sourabh-Pukale, @wtfiwtz, @iwillow, @WillDamon, @AlicanAkkus, @budlinville, @wjdfx, @victmo
